# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f96264f1657809d221ef0cd7e5e00a1b96be99e19e501762ac514ba0b30cd3ab3970902ca2d16c2ee671622a0348070a6d0809f3c971827f0b05fc9f972fcae

test:
  secret_key_base: 66db7e04661770f319f06cbe499b2d5f5fdf4817e4b38bca6f6f75155d8c977a3068150ab6dbd159dadd93c02ecd015395ee4ead99a716b151c7c4f7739d22a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
